import type { Testimonial } from "./types"

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Rahul Mehta",
    designation: "CEO, TechCorp",
    quote: "Geo SofTech completely transformed our online presence.",
    rating: 5,
    photo: "/rahul-mehta-portrait.png",
    logo: "/techcorp-logo.png",
    video: null,
    link: "/case-studies/techcorp",
    category: "Technology",
  },
  {
    id: 2,
    name: "Priya Sharma",
    designation: "Marketing Head, GreenWorld",
    quote: "The best web development team we have ever worked with.",
    rating: 4,
    photo: "/priya-sharma-portrait.png",
    logo: "/greenworld-logo.png",
    video: null,
    link: "/case-studies/greenworld",
    category: "Marketing",
  },
  {
    id: 3,
    name: "David Chen",
    designation: "Founder, FinPeak",
    quote: "Performance, accessibility, and SEO exceeded expectations.",
    rating: 5,
    photo: "/david-chen-portrait.png",
    logo: "/finpeak-logo.png",
    video: null,
    link: "/case-studies/finpeak",
    category: "Finance",
  },
  {
    id: 4,
    name: "Ana Rodriguez",
    designation: "CTO, HealthSphere",
    quote: "Seamless collaboration and impeccable delivery.",
    rating: 5,
    photo: "/ana-rodriguez-portrait.png",
    logo: "/healthsphere-logo.png",
    video: null,
    link: "/case-studies/healthsphere",
    category: "Healthcare",
  },
  {
    id: 5,
    name: "Liam O’Connor",
    designation: "COO, BuildRight",
    quote: "Robust architecture and delightful UX.",
    rating: 5,
    photo: "/liam-oconnor-portrait.png",
    logo: "/buildright-logo.png",
    video: null,
    link: "/case-studies/buildright",
    category: "Construction",
  },
  {
    id: 6,
    name: "Sara Ahmed",
    designation: "Product Lead, EduNova",
    quote: "Their attention to detail is unmatched.",
    rating: 4,
    photo: "/sara-ahmed-portrait.png",
    logo: "/edunova-logo.png",
    video: null,
    link: "/case-studies/edunova",
    category: "Education",
  },
]
