import type { Testimonial } from "./types"

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Rohan Desai",
    designation: "Founder, TaxEase Solutions",
    quote: "Finmates.in simplified our entire company registration and GST process. Their team is reliable and efficient!",
    rating: 5,
    photo: "https://randomuser.me/api/portraits/men/32.jpg",
    logo: "https://img.icons8.com/color/96/tax.png",
    video: null,
    link: "/case-studies/taxease",
    category: "Business Registration",
  },
  {
    id: 2,
    name: "Neha Kapoor",
    designation: "Finance Manager, GrowthPath Advisors",
    quote: "The Finmates platform is intuitive and makes compliance effortless. Highly recommend their services.",
    rating: 4,
    photo: "https://randomuser.me/api/portraits/women/44.jpg",
    logo: "https://img.icons8.com/color/96/money-bag.png", // ✅ Working replacement
    video: null,
    link: "/case-studies/growthpath",
    category: "Financial Services",
  },
  {
    id: 3,
    name: "Arjun Patel",
    designation: "Director, StartupNest",
    quote: "From company setup to filings, Finmates handled everything smoothly and professionally.",
    rating: 5,
    photo: "https://randomuser.me/api/portraits/men/45.jpg",
    logo: "https://img.icons8.com/color/96/rocket--v1.png", // ✅ Working startup logo
    video: null,
    link: "/case-studies/startupnest",
    category: "Startup Services",
  },
  {
    id: 4,
    name: "Isha Verma",
    designation: "Co-Founder, LegalEdge Consultants",
    quote: "Their expert team ensured all our compliance needs were met on time without any hassle.",
    rating: 5,
    photo: "https://randomuser.me/api/portraits/women/68.jpg",
    logo: "https://img.icons8.com/color/96/contract.png",
    video: null,
    link: "/case-studies/legaledge",
    category: "Compliance",
  },
  {
    id: 5,
    name: "Karan Malhotra",
    designation: "Owner, BizHive Enterprises",
    quote: "Excellent customer support and end-to-end solutions for small business management.",
    rating: 4,
    photo: "https://randomuser.me/api/portraits/men/51.jpg",
    logo: "https://img.icons8.com/color/96/business.png",
    video: null,
    link: "/case-studies/bizhive",
    category: "Business Management",
  },
  {
    id: 6,
    name: "Sneha Iyer",
    designation: "Operations Head, CloudBooks India",
    quote: "Thanks to Finmates, our accounting and tax filings are now completely automated and stress-free.",
    rating: 5,
    photo: "https://randomuser.me/api/portraits/women/29.jpg",
    logo: "https://img.icons8.com/color/96/accounting.png",
    video: null,
    link: "/case-studies/cloudbooks",
    category: "Accounting",
  },
];
